navbar:
  - index: index
  # - anna
  # - works
  # - Clicks: clicks
  # - Index: tags
  # - wiki
  # - notes
  # - posts
baseURL: https://hegde.live/
siteScripts:
  # - nav.js
  # - expand.js
  - animation.js
author: Aditya Hegde
