navbar:
  # - index: index.html
  - index: tags.html
  - clicks: clicks.html
  - about: about.html
  - cv: cv.pdf
  # - anna
  # - works
  # - Clicks: clicks
  # - wiki
  # - notes
  # - posts
baseURL: https://hegde.live/
siteScripts:
    - search-blur.js
    - animation.js
  # - nav.js
  # - expand.js
author: Aditya Hegde
